/* countries.js — full country list (EN/KO) for residence-country selects.
   Exposes window.COUNTRIES (array of {c: ISO2, en, ko}) and
   window.countryOptions(lang, selectedCode) -> <option> HTML string. */
(function () {
  window.COUNTRIES = [
    { c: 'AF', en: 'Afghanistan', ko: '아프가니스탄' },
    { c: 'AL', en: 'Albania', ko: '알바니아' },
    { c: 'DZ', en: 'Algeria', ko: '알제리' },
    { c: 'AD', en: 'Andorra', ko: '안도라' },
    { c: 'AO', en: 'Angola', ko: '앙골라' },
    { c: 'AG', en: 'Antigua and Barbuda', ko: '앤티가 바부다' },
    { c: 'AR', en: 'Argentina', ko: '아르헨티나' },
    { c: 'AM', en: 'Armenia', ko: '아르메니아' },
    { c: 'AU', en: 'Australia', ko: '오스트레일리아' },
    { c: 'AT', en: 'Austria', ko: '오스트리아' },
    { c: 'AZ', en: 'Azerbaijan', ko: '아제르바이잔' },
    { c: 'BS', en: 'Bahamas', ko: '바하마' },
    { c: 'BH', en: 'Bahrain', ko: '바레인' },
    { c: 'BD', en: 'Bangladesh', ko: '방글라데시' },
    { c: 'BB', en: 'Barbados', ko: '바베이도스' },
    { c: 'BY', en: 'Belarus', ko: '벨라루스' },
    { c: 'BE', en: 'Belgium', ko: '벨기에' },
    { c: 'BZ', en: 'Belize', ko: '벨리즈' },
    { c: 'BJ', en: 'Benin', ko: '베냉' },
    { c: 'BT', en: 'Bhutan', ko: '부탄' },
    { c: 'BO', en: 'Bolivia', ko: '볼리비아' },
    { c: 'BA', en: 'Bosnia and Herzegovina', ko: '보스니아 헤르체고비나' },
    { c: 'BW', en: 'Botswana', ko: '보츠와나' },
    { c: 'BR', en: 'Brazil', ko: '브라질' },
    { c: 'BN', en: 'Brunei', ko: '브루나이' },
    { c: 'BG', en: 'Bulgaria', ko: '불가리아' },
    { c: 'BF', en: 'Burkina Faso', ko: '부르키나파소' },
    { c: 'BI', en: 'Burundi', ko: '부룬디' },
    { c: 'CV', en: 'Cabo Verde', ko: '카보베르데' },
    { c: 'KH', en: 'Cambodia', ko: '캄보디아' },
    { c: 'CM', en: 'Cameroon', ko: '카메룬' },
    { c: 'CA', en: 'Canada', ko: '캐나다' },
    { c: 'CF', en: 'Central African Republic', ko: '중앙아프리카공화국' },
    { c: 'TD', en: 'Chad', ko: '차드' },
    { c: 'CL', en: 'Chile', ko: '칠레' },
    { c: 'CN', en: 'China', ko: '중국' },
    { c: 'CO', en: 'Colombia', ko: '콜롬비아' },
    { c: 'KM', en: 'Comoros', ko: '코모로' },
    { c: 'CG', en: 'Congo (Republic)', ko: '콩고공화국' },
    { c: 'CD', en: 'Congo (DRC)', ko: '콩고민주공화국' },
    { c: 'CR', en: 'Costa Rica', ko: '코스타리카' },
    { c: 'CI', en: "Côte d'Ivoire", ko: '코트디부아르' },
    { c: 'HR', en: 'Croatia', ko: '크로아티아' },
    { c: 'CU', en: 'Cuba', ko: '쿠바' },
    { c: 'CY', en: 'Cyprus', ko: '키프로스' },
    { c: 'CZ', en: 'Czechia', ko: '체코' },
    { c: 'DK', en: 'Denmark', ko: '덴마크' },
    { c: 'DJ', en: 'Djibouti', ko: '지부티' },
    { c: 'DM', en: 'Dominica', ko: '도미니카연방' },
    { c: 'DO', en: 'Dominican Republic', ko: '도미니카공화국' },
    { c: 'EC', en: 'Ecuador', ko: '에콰도르' },
    { c: 'EG', en: 'Egypt', ko: '이집트' },
    { c: 'SV', en: 'El Salvador', ko: '엘살바도르' },
    { c: 'GQ', en: 'Equatorial Guinea', ko: '적도기니' },
    { c: 'ER', en: 'Eritrea', ko: '에리트레아' },
    { c: 'EE', en: 'Estonia', ko: '에스토니아' },
    { c: 'SZ', en: 'Eswatini', ko: '에스와티니' },
    { c: 'ET', en: 'Ethiopia', ko: '에티오피아' },
    { c: 'FJ', en: 'Fiji', ko: '피지' },
    { c: 'FI', en: 'Finland', ko: '핀란드' },
    { c: 'FR', en: 'France', ko: '프랑스' },
    { c: 'GA', en: 'Gabon', ko: '가봉' },
    { c: 'GM', en: 'Gambia', ko: '감비아' },
    { c: 'GE', en: 'Georgia', ko: '조지아' },
    { c: 'DE', en: 'Germany', ko: '독일' },
    { c: 'GH', en: 'Ghana', ko: '가나' },
    { c: 'GR', en: 'Greece', ko: '그리스' },
    { c: 'GD', en: 'Grenada', ko: '그레나다' },
    { c: 'GT', en: 'Guatemala', ko: '과테말라' },
    { c: 'GN', en: 'Guinea', ko: '기니' },
    { c: 'GW', en: 'Guinea-Bissau', ko: '기니비사우' },
    { c: 'GY', en: 'Guyana', ko: '가이아나' },
    { c: 'HT', en: 'Haiti', ko: '아이티' },
    { c: 'HN', en: 'Honduras', ko: '온두라스' },
    { c: 'HU', en: 'Hungary', ko: '헝가리' },
    { c: 'IS', en: 'Iceland', ko: '아이슬란드' },
    { c: 'IN', en: 'India', ko: '인도' },
    { c: 'ID', en: 'Indonesia', ko: '인도네시아' },
    { c: 'IR', en: 'Iran', ko: '이란' },
    { c: 'IQ', en: 'Iraq', ko: '이라크' },
    { c: 'IE', en: 'Ireland', ko: '아일랜드' },
    { c: 'IL', en: 'Israel', ko: '이스라엘' },
    { c: 'IT', en: 'Italy', ko: '이탈리아' },
    { c: 'JM', en: 'Jamaica', ko: '자메이카' },
    { c: 'JP', en: 'Japan', ko: '일본' },
    { c: 'JO', en: 'Jordan', ko: '요르단' },
    { c: 'KZ', en: 'Kazakhstan', ko: '카자흐스탄' },
    { c: 'KE', en: 'Kenya', ko: '케냐' },
    { c: 'KI', en: 'Kiribati', ko: '키리바시' },
    { c: 'KW', en: 'Kuwait', ko: '쿠웨이트' },
    { c: 'KG', en: 'Kyrgyzstan', ko: '키르기스스탄' },
    { c: 'LA', en: 'Laos', ko: '라오스' },
    { c: 'LV', en: 'Latvia', ko: '라트비아' },
    { c: 'LB', en: 'Lebanon', ko: '레바논' },
    { c: 'LS', en: 'Lesotho', ko: '레소토' },
    { c: 'LR', en: 'Liberia', ko: '라이베리아' },
    { c: 'LY', en: 'Libya', ko: '리비아' },
    { c: 'LI', en: 'Liechtenstein', ko: '리히텐슈타인' },
    { c: 'LT', en: 'Lithuania', ko: '리투아니아' },
    { c: 'LU', en: 'Luxembourg', ko: '룩셈부르크' },
    { c: 'MG', en: 'Madagascar', ko: '마다가스카르' },
    { c: 'MW', en: 'Malawi', ko: '말라위' },
    { c: 'MY', en: 'Malaysia', ko: '말레이시아' },
    { c: 'MV', en: 'Maldives', ko: '몰디브' },
    { c: 'ML', en: 'Mali', ko: '말리' },
    { c: 'MT', en: 'Malta', ko: '몰타' },
    { c: 'MH', en: 'Marshall Islands', ko: '마셜제도' },
    { c: 'MR', en: 'Mauritania', ko: '모리타니' },
    { c: 'MU', en: 'Mauritius', ko: '모리셔스' },
    { c: 'MX', en: 'Mexico', ko: '멕시코' },
    { c: 'FM', en: 'Micronesia', ko: '미크로네시아' },
    { c: 'MD', en: 'Moldova', ko: '몰도바' },
    { c: 'MC', en: 'Monaco', ko: '모나코' },
    { c: 'MN', en: 'Mongolia', ko: '몽골' },
    { c: 'ME', en: 'Montenegro', ko: '몬테네그로' },
    { c: 'MA', en: 'Morocco', ko: '모로코' },
    { c: 'MZ', en: 'Mozambique', ko: '모잠비크' },
    { c: 'MM', en: 'Myanmar', ko: '미얀마' },
    { c: 'NA', en: 'Namibia', ko: '나미비아' },
    { c: 'NR', en: 'Nauru', ko: '나우루' },
    { c: 'NP', en: 'Nepal', ko: '네팔' },
    { c: 'NL', en: 'Netherlands', ko: '네덜란드' },
    { c: 'NZ', en: 'New Zealand', ko: '뉴질랜드' },
    { c: 'NI', en: 'Nicaragua', ko: '니카라과' },
    { c: 'NE', en: 'Niger', ko: '니제르' },
    { c: 'NG', en: 'Nigeria', ko: '나이지리아' },
    { c: 'KP', en: 'North Korea', ko: '북한' },
    { c: 'MK', en: 'North Macedonia', ko: '북마케도니아' },
    { c: 'NO', en: 'Norway', ko: '노르웨이' },
    { c: 'OM', en: 'Oman', ko: '오만' },
    { c: 'PK', en: 'Pakistan', ko: '파키스탄' },
    { c: 'PW', en: 'Palau', ko: '팔라우' },
    { c: 'PS', en: 'Palestine', ko: '팔레스타인' },
    { c: 'PA', en: 'Panama', ko: '파나마' },
    { c: 'PG', en: 'Papua New Guinea', ko: '파푸아뉴기니' },
    { c: 'PY', en: 'Paraguay', ko: '파라과이' },
    { c: 'PE', en: 'Peru', ko: '페루' },
    { c: 'PH', en: 'Philippines', ko: '필리핀' },
    { c: 'PL', en: 'Poland', ko: '폴란드' },
    { c: 'PT', en: 'Portugal', ko: '포르투갈' },
    { c: 'QA', en: 'Qatar', ko: '카타르' },
    { c: 'RO', en: 'Romania', ko: '루마니아' },
    { c: 'RU', en: 'Russia', ko: '러시아' },
    { c: 'RW', en: 'Rwanda', ko: '르완다' },
    { c: 'KN', en: 'Saint Kitts and Nevis', ko: '세인트키츠 네비스' },
    { c: 'LC', en: 'Saint Lucia', ko: '세인트루시아' },
    { c: 'VC', en: 'Saint Vincent and the Grenadines', ko: '세인트빈센트 그레나딘' },
    { c: 'WS', en: 'Samoa', ko: '사모아' },
    { c: 'SM', en: 'San Marino', ko: '산마리노' },
    { c: 'ST', en: 'Sao Tome and Principe', ko: '상투메 프린시페' },
    { c: 'SA', en: 'Saudi Arabia', ko: '사우디아라비아' },
    { c: 'SN', en: 'Senegal', ko: '세네갈' },
    { c: 'RS', en: 'Serbia', ko: '세르비아' },
    { c: 'SC', en: 'Seychelles', ko: '세이셸' },
    { c: 'SL', en: 'Sierra Leone', ko: '시에라리온' },
    { c: 'SG', en: 'Singapore', ko: '싱가포르' },
    { c: 'SK', en: 'Slovakia', ko: '슬로바키아' },
    { c: 'SI', en: 'Slovenia', ko: '슬로베니아' },
    { c: 'SB', en: 'Solomon Islands', ko: '솔로몬제도' },
    { c: 'SO', en: 'Somalia', ko: '소말리아' },
    { c: 'ZA', en: 'South Africa', ko: '남아프리카공화국' },
    { c: 'KR', en: 'South Korea', ko: '대한민국' },
    { c: 'SS', en: 'South Sudan', ko: '남수단' },
    { c: 'ES', en: 'Spain', ko: '스페인' },
    { c: 'LK', en: 'Sri Lanka', ko: '스리랑카' },
    { c: 'SD', en: 'Sudan', ko: '수단' },
    { c: 'SR', en: 'Suriname', ko: '수리남' },
    { c: 'SE', en: 'Sweden', ko: '스웨덴' },
    { c: 'CH', en: 'Switzerland', ko: '스위스' },
    { c: 'SY', en: 'Syria', ko: '시리아' },
    { c: 'TW', en: 'Taiwan', ko: '대만' },
    { c: 'TJ', en: 'Tajikistan', ko: '타지키스탄' },
    { c: 'TZ', en: 'Tanzania', ko: '탄자니아' },
    { c: 'TH', en: 'Thailand', ko: '태국' },
    { c: 'TL', en: 'Timor-Leste', ko: '동티모르' },
    { c: 'TG', en: 'Togo', ko: '토고' },
    { c: 'TO', en: 'Tonga', ko: '통가' },
    { c: 'TT', en: 'Trinidad and Tobago', ko: '트리니다드 토바고' },
    { c: 'TN', en: 'Tunisia', ko: '튀니지' },
    { c: 'TR', en: 'Türkiye', ko: '튀르키예' },
    { c: 'TM', en: 'Turkmenistan', ko: '투르크메니스탄' },
    { c: 'TV', en: 'Tuvalu', ko: '투발루' },
    { c: 'UG', en: 'Uganda', ko: '우간다' },
    { c: 'UA', en: 'Ukraine', ko: '우크라이나' },
    { c: 'AE', en: 'United Arab Emirates', ko: '아랍에미리트' },
    { c: 'GB', en: 'United Kingdom', ko: '영국' },
    { c: 'US', en: 'United States', ko: '미국' },
    { c: 'UY', en: 'Uruguay', ko: '우루과이' },
    { c: 'UZ', en: 'Uzbekistan', ko: '우즈베키스탄' },
    { c: 'VU', en: 'Vanuatu', ko: '바누아투' },
    { c: 'VA', en: 'Vatican City', ko: '바티칸' },
    { c: 'VE', en: 'Venezuela', ko: '베네수엘라' },
    { c: 'VN', en: 'Vietnam', ko: '베트남' },
    { c: 'YE', en: 'Yemen', ko: '예멘' },
    { c: 'ZM', en: 'Zambia', ko: '잠비아' },
    { c: 'ZW', en: 'Zimbabwe', ko: '짐바브웨' }
  ];

  window.countryOptions = function (lang, selected) {
    var isKo = String(lang || '').toLowerCase().indexOf('ko') === 0;
    var list = window.COUNTRIES.slice().sort(function (a, b) {
      return (isKo ? a.ko.localeCompare(b.ko, 'ko') : a.en.localeCompare(b.en));
    });
    return list.map(function (x) {
      var label = isKo ? x.ko : x.en;
      var sel = (selected && (selected === x.c || selected === x.en || selected === x.ko)) ? ' selected' : '';
      return '<option value="' + x.c + '"' + sel + '>' + label + '</option>';
    }).join('');
  };
})();
